### ISSUE TITLE
state.location

### ISSUE THREAD

**Issue by morriswinkler-simplesurance** [donovantc/find-me-food#6]
state.location should be only pulled once. Currently, it is pulled by _getLocationAsync in App.js and MapDisplay.js (getLocationAsync) [ i actually copied the example to the point :P].

The location should also be refreshed from time to time, at least when the App gets back in focus while having left it before.

**Comment by donovantc** [comment]
Yeah I  agree, good that you moved it to App.js. We can take it out of MapDisplay.js and pass it as prop (location) to the MapDisplay component.

**Comment by donovantc** [comment]
Done!

**Comment by morriswinkler-simplesurance** [comment]
what about http://facebook.github.io/react-native/releases/0.39/docs/appstate.html#appstate
